# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [27]:
import pandas as pd
import numpy as np

## Load the data

In [28]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [29]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create the targets

In [30]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [31]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [32]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [33]:
data_preprocessed['Excessive Absenteeism'] = targets

In [34]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [35]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [36]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)

In [37]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

# Select the inputs for the regression

In [38]:
data_with_targets.shape

(700, 15)

In [39]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [40]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

# Standardize the data

In [41]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [42]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [43]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [44]:
columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']

In [50]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [52]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\User\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [53]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [54]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.030796        -0.800950   
1           0         0         0         0     0.030796        -0.800950   
2           0         0         0         1     0.030796        -0.232900   
3           1         0         0         0     0.030796         0.335149   
4           0         0         0         1     0.030796         0.335149   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.568019        -0.232900   
696         1         0         0         0    -0.568019        -0.232900   
697         1         0         0         0    -0.568019         0.335149   
698         0         0         0         1    -0.568019         0.335149   
699         0         0         0         1    -0.568019         0.335149   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [55]:
scaled_inputs.shape

(700, 14)

# Split the data into train & test and shuffle

In [56]:
from sklearn.model_selection import train_test_split

# Split

In [57]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 251         0         0         0         0     0.030796         0.335149   
 115         0         0         0         1    -0.568019         2.039298   
 331         1         0         0         0     1.228426         0.903199   
 377         1         0         0         0    -1.466241         0.335149   
 146         0         0         0         1    -1.466241        -1.368999   
 ..        ...       ...       ...       ...          ...              ...   
 483         0         0         0         1     0.330204        -0.800950   
 88          0         0         0         1     1.228426        -0.232900   
 636         0         0         0         1    -1.166834        -1.368999   
 192         0         0         0         1     0.030796        -1.368999   
 430         0         0         0         1     1.228426         2.039298   
 
      Transportation Expense  Distance to Work       Age  \
 2

In [58]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [59]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [60]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


# Logistic regression with sklearn

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Training the model

In [62]:
reg = LogisticRegression()

In [63]:
reg.fit(x_train,y_train)

LogisticRegression()

In [64]:
reg.score(x_train,y_train)

0.7660714285714286

# Manually check the accuracy

In [65]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [66]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [67]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [68]:
np.sum((model_outputs == y_train))

429

In [69]:
model_outputs.shape[0]

560

In [70]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7660714285714286

# Finding the intercepts and coefficients

In [71]:
reg.intercept_

array([-1.60991897])

In [72]:
reg.coef_

array([[ 2.78809595,  0.92273475,  3.10358519,  0.81724476,  0.01379249,
        -0.07594179,  0.62737945, -0.02990801, -0.17344994, -0.02273184,
         0.2816181 , -0.27058935,  0.36063506, -0.27446609]])

In [73]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [74]:
feature_name = unscaled_inputs.columns.values

In [75]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                  Reason_1     2.788096
1                  Reason_2     0.922735
2                  Reason_3     3.103585
3                  Reason_4     0.817245
4               Month Value     0.013792
5           Day of the Week    -0.075942
6    Transportation Expense     0.627379
7          Distance to Work    -0.029908
8                       Age    -0.173450
9   Daily Work Load Average    -0.022732
10          Body Mass Index     0.281618
11                Education    -0.270589
12                 Children     0.360635
13                     Pets    -0.274466

In [76]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -1.609919
1                  Reason_1     2.788096
2                  Reason_2     0.922735
3                  Reason_3     3.103585
4                  Reason_4     0.817245
5               Month Value     0.013792
6           Day of the Week    -0.075942
7    Transportation Expense     0.627379
8          Distance to Work    -0.029908
9                       Age    -0.173450
10  Daily Work Load Average    -0.022732
11          Body Mass Index     0.281618
12                Education    -0.270589
13                 Children     0.360635
14                     Pets    -0.274466

# Interpreting the coefficients

In [77]:
summary_table['odds_ratio'] = np.exp(summary_table.Coefficient)

In [78]:
summary_table

Feature name  Coefficient  odds_ratio
0                 Intercept    -1.609919    0.199904
1                  Reason_1     2.788096   16.250049
2                  Reason_2     0.922735    2.516162
3                  Reason_3     3.103585   22.277678
4                  Reason_4     0.817245    2.264253
5               Month Value     0.013792    1.013888
6           Day of the Week    -0.075942    0.926870
7    Transportation Expense     0.627379    1.872697
8          Distance to Work    -0.029908    0.970535
9                       Age    -0.173450    0.840759
10  Daily Work Load Average    -0.022732    0.977525
11          Body Mass Index     0.281618    1.325273
12                Education    -0.270589    0.762930
13                 Children     0.360635    1.434240
14                     Pets    -0.274466    0.759978

In [79]:
summary_table.sort_values('odds_ratio', ascending=False)

Feature name  Coefficient  odds_ratio
3                  Reason_3     3.103585   22.277678
1                  Reason_1     2.788096   16.250049
2                  Reason_2     0.922735    2.516162
4                  Reason_4     0.817245    2.264253
7    Transportation Expense     0.627379    1.872697
13                 Children     0.360635    1.434240
11          Body Mass Index     0.281618    1.325273
5               Month Value     0.013792    1.013888
10  Daily Work Load Average    -0.022732    0.977525
8          Distance to Work    -0.029908    0.970535
6           Day of the Week    -0.075942    0.926870
9                       Age    -0.173450    0.840759
12                Education    -0.270589    0.762930
14                     Pets    -0.274466    0.759978
0                 Intercept    -1.609919    0.199904

# Testing the model

In [80]:
reg.score(x_test,y_test)

0.7571428571428571

In [81]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75835265, 0.24164735],
       [0.62498802, 0.37501198],
       [0.45440874, 0.54559126],
       [0.77426   , 0.22574   ],
       [0.07523779, 0.92476221],
       [0.28681936, 0.71318064],
       [0.30073948, 0.69926052],
       [0.11193452, 0.88806548],
       [0.75347284, 0.24652716],
       [0.75760515, 0.24239485],
       [0.49756376, 0.50243624],
       [0.18139028, 0.81860972],
       [0.06978241, 0.93021759],
       [0.67883884, 0.32116116],
       [0.27957168, 0.72042832],
       [0.49797848, 0.50202152],
       [0.51589736, 0.48410264],
       [0.55051804, 0.44948196],
       [0.38313924, 0.61686076],
       [0.05676825, 0.94323175],
       [0.73363565, 0.26636435],
       [0.76663108, 0.23336892],
       [0.44371138, 0.55628862],
       [0.46099097, 0.53900903],
       [0.22525807, 0.77474193],
       [0.7535073 , 0.2464927 ],
       [0.49490369, 0.50509631],
       [0.87493323, 0.12506677],
       [0.23623712, 0.76376288],
       [0.75882465, 0.24117535],
       [0.

In [82]:
predicted_proba.shape

(140, 2)

In [83]:
predicted_proba[:,1]

array([0.24164735, 0.37501198, 0.54559126, 0.22574   , 0.92476221,
       0.71318064, 0.69926052, 0.88806548, 0.24652716, 0.24239485,
       0.50243624, 0.81860972, 0.93021759, 0.32116116, 0.72042832,
       0.50202152, 0.48410264, 0.44948196, 0.61686076, 0.94323175,
       0.26636435, 0.23336892, 0.55628862, 0.53900903, 0.77474193,
       0.2464927 , 0.50509631, 0.12506677, 0.76376288, 0.24117535,
       0.39918393, 0.72047675, 0.68231942, 0.50353998, 0.23336892,
       0.57784928, 0.26023495, 0.75743911, 0.45350431, 0.5903656 ,
       0.25199485, 0.45191141, 0.24236434, 0.39437621, 0.8030637 ,
       0.63740889, 0.73819425, 0.24982618, 0.26669706, 0.21539655,
       0.51862303, 0.3061877 , 0.68974674, 0.26077087, 0.84058793,
       0.4196596 , 0.91483074, 0.29400699, 0.31478632, 0.30997231,
       0.73234382, 0.66455837, 0.28795543, 0.78613859, 0.24913302,
       0.24371337, 0.07494652, 0.24870204, 0.76501224, 0.32537572,
       0.25137072, 0.31368394, 0.89488667, 0.44831462, 0.61226

# Save the model

In [84]:
import pickle

In [85]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [86]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)